### ISSUE TITLE
TL500 chart fails on StackRox deployment

### ISSUE THREAD

**Issue by jfilipcz** [rht-labs/enablement-framework#102]
TL500 Chart (v3.0.4) is failing with: 
```
client.go:519: [debug] Add/Modify event for configure-stackrox-integration: MODIFIED
upgrade.go:369: [debug] warning: Upgrade "tl500" failed: post-upgrade hooks failed: job failed: BackoffLimitExceeded
Error: UPGRADE FAILED: post-upgrade hooks failed: job failed: BackoffLimitExceeded
helm.go:81: [debug] post-upgrade hooks failed: job failed: BackoffLimitExceeded
UPGRADE FAILED
```
I was not able to pull logs from the actual job/pod but I will give it another try

values related to stackrox that were used at deployment: 
```
stackrox-chart:
  enabled: true
  stackrox:
    clusterName: tl500
    namespace: stackrox

```
