### ISSUE TITLE
🐂 monitoring rbac fails for student user 🐂

### ISSUE THREAD

**Issue by eformat** [rht-labs/enablement-framework#81]
Getting this error when trying the monitoring section as a student

https://rht-labs.com/tech-exercise/#/4-return-of-the-monitoring/1-enable-monitoring

Step 1.
```
$ oc get servicemonitor -n ${TEAM_NAME}-test -o yaml

Error from server (Forbidden): servicemonitors.monitoring.coreos.com is forbidden: User "mike" cannot list resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "ateam-test"
```

Seems we need this applied in the rbac

```
cat <<EOF | oc apply -f-
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tl500-monitoring-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: tl500-users
EOF
```
